name: Mailchimp
version: 1.3.7
description: Subscribes a registering user or contact form to a Mailchimp list
url: https://github.com/edalzell/statamic-mailchimp
developer: Erin Dalzell
developer_url: https://silentzconsulting.com
