fields:
  mailchimp_key:
    type: text
    validate: required
  user_section:
    type: section
    display: Users
  add_new_users:
    type: toggle
    display: Add New Users?
    width: 33
  user_disable_opt_in:
    type: toggle
    display: Disable Opt In?
    width: 33
    show_when:
      add_new_users: true
  user_check_permission:
    type: toggle
    display: Check Permission?
    width: 33
    show_when:
      add_new_users: true
  user_mailchimp_list_id:
    type: text
    display: 'Mailchimp List ID'
    validate: required_if:add_new_users,true
    width: 50
    show_when:
      add_new_users: true
  user_permission_field:
    type: suggest
    mode: mailchimp.user_fields
    display: Permission Field
    max_items: 1
    validate: required_if:user_check_permission,true
    width: 50
    show_when:
      add_new_users: true
      user_check_permission: true
  user_merge_fields:
    type: grid
    display: 'Merge & Form Field Mapping'
    fields:
      tag:
        type: text
        display: Mailchimp Merge Tag
        instructions: "**Case Matters**! Upper case only please."
        width: 50
      field_name:
        type: text
        display: Field Name
        instructions: '&nbsp;'
        width: 50
    add_row: Add Merge Field
    show_when:
      add_new_users: true
  forms_section:
    type: section
    display: Forms
  forms:
    type: grid
    display: 'Please save each row as you go. i.e. add a form, save it, add another.'
    fields:
      mailchimp_list_id:
        type: text
        display: 'Mailchimp List ID'
        validate: required
        width: 20
      disable_opt_in:
        type: toggle
        display: Disable Opt In?
        width: 20
      form:
        type: form
        max_items: 1
        width: 20
      check_permission:
        type: toggle
        display: Check Permission?
        width: 20
      permission_field:
        type: mailchimp
        display: ' '
        validate: required
        width: 20
        show_when:
          check_permission: true
      merge_fields:
        type: grid
        display: ' '
        fields:
          tag:
            type: text
            display: Mailchimp Merge Tag
            instructions: "**Case Matters**! Upper case only please."
          field_name:
            type: text
            display: Field Name
        add_row: Add Merge Field
    mode: stacked
    min_rows: "1"
    add_row: Add Form
