title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        width: 66
      slug:
        type: text
        width: 33
        localizable: true
      content:
        type: markdown
        display: Content
taxonomies: true
hide: true
