sections:
  project-layout:
    display: Layout
    fields:
      blocks:
        sets:
          layout-text:
            display: Tekstblok
            instructions: 'Een tekstblok, al dan niet met titel.'
            fields:
              layout-text__title:
                type: text
                display: Titel
              layout-text__redactor:
                settings: Standard
                restrict_assets: false
                type: redactor
                display: Tekst
              id_on_page:
                type: text
                display: 'Naam op pagina'
          layout-article:
            display: 'Artikel in de kijker'
            fields:
              layout-article__id:
                max_items: '1'
                collection:
                  - news
                mode: panes
                type: collection
                instructions: 'Zet een artikel in de kijker.'
                display: Artikel
              id_on_page:
                type: text
                display: 'Naam op pagina'
          layout-scroll:
            display: 'Voorbijscrollende tekst'
            fields:
              layout-scroll__text:
                type: text
                display: Tekst
              naam_op_pagina:
                type: text
                display: 'Naam op pagina'
          layout-week:
            display: 'Deze week'
            fields:
              field_1:
                fieldset: schedule-day
                type: partial
                display: 'Field 1'
              field_2:
                fieldset: schedule-day
                type: partial
                display: 'Field 2'
          schedule:
            display: Weekplanning
            instructions: 'Maak hier de planning van de week op'
            fields:
              block_title:
                type: text
                display: Titel
              schedule-replicator:
                sets:
                  weekdag:
                    display: Weekdag
                    fields:
                      weekdag:
                        fieldset: schedule-day
                        type: partial
                        display: Weekdag
                type: replicator
                display: Weekplanning
              id_on_page:
                type: text
                display: 'Naam op pagina'
          layout-widget:
            display: Widget
            fields:
              widget:
                options:
                  calendar: Kalender
                  projects: Projects
                  mailing: Mailing
                type: select
                instructions: 'Kies een van de widgets om op de pagina te tonen.'
                display: Widget
          afbeeldingen:
            display: Afbeeldingen
            fields:
              image:
                container: main
                folder: /
                restrict: false
                type: assets
                display: Afbeelding
              width:
                options:
                  full: 'extra breed'
                  normal: 'Volledige breedte'
                type: select
                display: width
              naam_op_pagina:
                type: text
                display: 'Naam op pagina'
          locatie:
            display: Locatie
            fields:
              titel:
                type: text
                display: Titel
              text:
                restrict_assets: false
                type: redactor
                display: Tekst
              kaart:
                type: text
                display: Kaart
              id_on_page:
                type: text
                display: 'Naam op pagina'
          knoppen:
            display: Knoppen
            fields:
              titel:
                type: text
                display: Titel
              id_on_page:
                type: text
                display: 'Naam op pagina'
          tekst_horizontaal:
            display: 'tekst horizontaal'
            fields:
              block_title:
                type: text
                display: Titel
              blocks:
                sets:
                  text:
                    display: text
                    fields:
                      title:
                        type: text
                        display: Titel
                      text:
                        restrict_assets: false
                        type: redactor
                        display: Tekst
                      image:
                        container: main
                        folder: /
                        restrict: false
                        type: assets
                        display: Afbeelding
                type: replicator
                display: blokjes
              id_on_page:
                type: text
                display: 'Naam op pagina'
          video:
            display: video
            fields:
              title:
                type: text
                display: Titel
              video:
                type: video
                display: video
        type: replicator
        instructions: 'Dit is de basisstructuur van de hele pagina.'
        display: layout
        localizable: true
  sidebar:
    display: Algemeen
    fields:
      title:
        display: Titel
        type: text
        localizable: true
      thumbnail:
        container: main
        folder: /
        restrict: false
        max_files: 1
        type: assets
        display: 'Foto voor verwijzing'
  menu:
    display: Menu
    fields:
      menu:
        fieldset: menu_container
        type: partial
        localizable: true
        display: Menu
taxonomies: true
title: Project
hide: true
